### PR TITLE
Replace Webviz to Foxglove-studio

### PR DESCRIPTION
**Pull request by WatanabeToshimitsu**
## What?
Replace Webviz to Foxglove-studio

## Why?
Foxglove Studio began as a fork of Webviz, and it is developed more actively than webviz, and consisted modern framework. So we want to migrate to foxglove-studio.
 
## See also
https://foxglove.dev/blog/foxglove-studio-vs-webviz

### CODE REVIEW

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-scene-viewer/pull/93#" title="Author self-approved">WatanabeToshimitsu</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-scene-viewer).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-scene-viewer/blob/main/OWNERS)~~ [WatanabeToshimitsu]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by WatanabeToshimitsu** [comment]
とりあえずざっくり動く状態にしました

```
git checkout feature/use-foxglove-studio
git submodule update -r -i
yarn install
yarn workspace scene-viewer-panels run build
yarn workspace foxglove-studio run web:serve
```

と、順に実行すれば http://localhost:8080/ にアクセスして ↓ みたくざっくり動くものが見れるようになっているはずです
image

**Comment by hdl-service** [comment]
[Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.

**The list of commits with invalid commit messages**:

- [7a9b7c5](https://github.com/dataware-tools/app-scene-viewer/commits/7a9b7c587dd07bff158301347f0037c63da7e6d4) Add @testing-library/react-hooks to succeed in test of foxglove-studio

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by hdl-service** [comment]
[Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.

**The list of commits with invalid commit messages**:

- [7a9b7c5](https://github.com/dataware-tools/app-scene-viewer/commits/7a9b7c587dd07bff158301347f0037c63da7e6d4) Add @testing-library/react-hooks to succeed in test of foxglove-studio

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by WatanabeToshimitsu** [comment]
@d-hayashi 
とりあえず docker compose up すれば localhost:8080 で foxglove-studio が立ち上がるようになりました
現在の開発環境のバックエンドと、ざっくりではあるものの強調できてるっぽいので、恐らく大きな改変がなくともデプロイできるかと....
一応マニュフェストファイルを見てはみたんですが、どこを弄ればいいか確信が持てない部分が多かったので、お手隙の時に一度デプロイを試してもらえたりできますか....?

尚、[webviz では nginx のイメージをベースイメージとしていた](https://github.com/dataware-tools/webviz/blob/31839d2d963d23684cea1867d5ad1177eaff72df/Dockerfile-static-webviz#L43)と思うんですが、foxglove-studio は[caddy2](https://caddyserver.com/docs/quick-starts/static-files)を使って[静的ファイルを配信する方式](https://github.com/dataware-tools/foxglove-studio/blob/7e446635c557ce2d8bf2e739557dc7bb2f645fbe/Dockerfile#L10)を採用してたので、それに倣ってDockerfile と docker-compse.yaml を更新しています
もし nginx の方が都合が良いようだったら、特にこだわりはないのでその辺りは変えてもらって大丈夫です！

**Comment by d-hayashi** [comment]
了解です！

**Comment by hdl-service** [comment]
[Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.

**The list of commits with invalid commit messages**:

- [7a9b7c5](https://github.com/dataware-tools/app-scene-viewer/commits/7a9b7c587dd07bff158301347f0037c63da7e6d4) Add @testing-library/react-hooks to succeed in test of foxglove-studio

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by hdl-service** [comment]
[Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.

**The list of commits with invalid commit messages**:

- [7a9b7c5](https://github.com/dataware-tools/app-scene-viewer/commits/7a9b7c587dd07bff158301347f0037c63da7e6d4) Add @testing-library/react-hooks to succeed in test of foxglove-studio
- [fcefb44](https://github.com/dataware-tools/app-scene-viewer/commits/fcefb44e95d74e5b94d943ec2be2973cfee1faa7) Add @foxglove/studio-base to succeed for building scene-viewer-panels

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by hdl-service** [comment]
[Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.

**The list of commits with invalid commit messages**:

- [7a9b7c5](https://github.com/dataware-tools/app-scene-viewer/commits/7a9b7c587dd07bff158301347f0037c63da7e6d4) Add @testing-library/react-hooks to succeed in test of foxglove-studio
- [fcefb44](https://github.com/dataware-tools/app-scene-viewer/commits/fcefb44e95d74e5b94d943ec2be2973cfee1faa7) Add @foxglove/studio-base to succeed for building scene-viewer-panels

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by hdl-service** [comment]
[Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.

**The list of commits with invalid commit messages**:

- [7a9b7c5](https://github.com/dataware-tools/app-scene-viewer/commits/7a9b7c587dd07bff158301347f0037c63da7e6d4) Add @testing-library/react-hooks to succeed in test of foxglove-studio
- [fcefb44](https://github.com/dataware-tools/app-scene-viewer/commits/fcefb44e95d74e5b94d943ec2be2973cfee1faa7) Add @foxglove/studio-base to succeed for building scene-viewer-panels

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by hdl-service** [comment]
[Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.

**The list of commits with invalid commit messages**:

- [7a9b7c5](https://github.com/dataware-tools/app-scene-viewer/commits/7a9b7c587dd07bff158301347f0037c63da7e6d4) Add @testing-library/react-hooks to succeed in test of foxglove-studio
- [fcefb44](https://github.com/dataware-tools/app-scene-viewer/commits/fcefb44e95d74e5b94d943ec2be2973cfee1faa7) Add @foxglove/studio-base to succeed for building scene-viewer-panels

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by hdl-service** [comment]
[Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.

**The list of commits with invalid commit messages**:

- [7a9b7c5](https://github.com/dataware-tools/app-scene-viewer/commits/7a9b7c587dd07bff158301347f0037c63da7e6d4) Add @testing-library/react-hooks to succeed in test of foxglove-studio
- [fcefb44](https://github.com/dataware-tools/app-scene-viewer/commits/fcefb44e95d74e5b94d943ec2be2973cfee1faa7) Add @foxglove/studio-base to succeed for building scene-viewer-panels

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by hdl-service** [comment]
[Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.

**The list of commits with invalid commit messages**:

- [7a9b7c5](https://github.com/dataware-tools/app-scene-viewer/commits/7a9b7c587dd07bff158301347f0037c63da7e6d4) Add @testing-library/react-hooks to succeed in test of foxglove-studio
- [fcefb44](https://github.com/dataware-tools/app-scene-viewer/commits/fcefb44e95d74e5b94d943ec2be2973cfee1faa7) Add @foxglove/studio-base to succeed for building scene-viewer-panels

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by hdl-service** [comment]
[Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.

**The list of commits with invalid commit messages**:

- [7a9b7c5](https://github.com/dataware-tools/app-scene-viewer/commits/7a9b7c587dd07bff158301347f0037c63da7e6d4) Add @testing-library/react-hooks to succeed in test of foxglove-studio
- [fcefb44](https://github.com/dataware-tools/app-scene-viewer/commits/fcefb44e95d74e5b94d943ec2be2973cfee1faa7) Add @foxglove/studio-base to succeed for building scene-viewer-panels

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
